// Product Database with proper images
const products = [
    // SENSORS
    { id: 1, name: "Thermistor", 
        price: 80, category: "sensors", 
        description: "Temperature sensitive resistor", 
        image: "images/Thermistor.png.png " },
        
    { id: 2, name: "DHT11", price: 120, category: "sensors", description: "Digital temperature & humidity sensor", image: "images/DHT11.png" },
    { id: 3, name: "DS18B20", price: 100, category: "sensors", description: "Waterproof temperature sensor", image: "images/DS18B20.png.png " },
    { id: 4, name: "LM35", price: 100, category: "sensors", description: "Precision temperature sensor", image: "images/LM35.png.png " },
    { id: 5, name: "DHT22", price: 170, category: "sensors", description: "High precision temp & humidity sensor", image: "images/DHT22.png.png" },
    { id: 6, name: "MQ2", price: 120, category: "sensors", description: "Gas & smoke detection sensor", image: "images/MQ2.png.png" },
    { id: 7, name: "MQ135", price: 130, category: "sensors", description: "Air quality sensor module", image: "images/MQ135.png.png" },
    { id: 8, name: "LDR Module", price: 60, category: "sensors", description: "Light intensity detection module", image: "images/LDR.png.png" },
    { id: 9, name: "IR Sensor", price: 50, category: "sensors", description: "Infrared obstacle detection sensor", image: "images/IR.png.png" },
    { id: 10, name: "Color Sensor", price: 450, category: "sensors", description: "RGB color detection module", image: "images/Color.png.png" },
    { id: 11, name: "Sound & Voice Sensor", price: 80, category: "sensors", description: "Sound detection module", image: "images/Sound.png.png" },
    { id: 12, name: "Vibration Sensor", price: 80, category: "sensors", description: "Vibration & shock detection", image: "images/Vibration.png.png" },
    { id: 13, name: "Ultrasonic Sensor", price: 90, category: "sensors", description: "HC-SR04 distance sensor", image: "images/Ultrasonic.png.png" },
    { id: 14, name: "Soil Moisture Sensor", price: 80, category: "sensors", description: "Moisture detection for plants", image: "images/soil_moisture.png.png" },
    { id: 15, name: "Touch Sensor", price: 40, category: "sensors", description: "Capacitive touch module", image: "images/Touch.png.png" },
    { id: 16, name: "Fingerprint Sensor", price: 1050, category: "sensors", description: "Biometric fingerprint module", image: "images/Fingerprint.png.png" },
    { id: 17, name: "RFID Module", price: 150, category: "sensors", description: "RF identification reader", image: "images/RFID.png.png" },
    { id: 18, name: "Rain Sensor", price: 80, category: "sensors", description: "Rainfall detection module", image: "images/Rain.png.png" },
    { id: 19, name: "IR Receiver with Remote", price: 70, category: "sensors", description: "IR receiver + remote control", image: "images/ir_receiver.png.png" },
    { id: 20, name: "MPU6050", price: 250, category: "sensors", description: "6-axis gyroscope & accelerometer", image: "images/MPU6050.png" },
    { id: 21, name: "PIR Sensor", price: 100, category: "sensors", description: "Motion detection sensor", image: "images/pir.png" },
    { id: 22, name: "Eye Blink Sensor", price: 200, category: "sensors", description: "Eye blink detection module", image: "images/EyeBlink.png" },
    { id: 23, name: "Voltage Sensor", price: 170, category: "sensors", description: "DC voltage measurement module", image: "images/voltagesensor (1).png" },
    { id: 24, name: "Current Sensor", price: 150, category: "sensors", description: "ACS712 current sensor", image: "images/Current.png" },
    
    // MICROCONTROLLERS
    { id: 25, name: "Arduino Uno SMD", price: 300, category: "microcontrollers", description: "Arduino Uno SMD (with cable)", image: "images/arduinosmd.png.png" },
    { id: 26, name: "Arduino Uno DIP", price: 550, category: "microcontrollers", description: "Arduino Uno DIP (with cable)", image: "images/arduinodip.png.png" },
    { id: 27, name: "ESP32", price: 390, category: "microcontrollers", description: "WiFi & Bluetooth dev board", image: "images/esp32.png.png" },
    { id: 28, name: "ESP8266", price: 350, category: "microcontrollers", description: "WiFi development board", image: "images/esp8266.png.png" },
    { id: 29, name: "ESP-01", price: 280, category: "microcontrollers", description: "ESP-01 WiFi (with programmer)", image: "images/esp01.png.png" },
    { id: 30, name: "XIAO ESP32 C3", price: 650, category: "microcontrollers", description: "Compact ESP32-C3 board", image: "images/xiao.png.png" },
    { id: 31, name: "Raspberry Pi Pico", price: 350, category: "microcontrollers", description: "RP2040 microcontroller", image: "images/pico.png.png" },
    { id: 32, name: "Raspberry Pi Pico W", price: 600, category: "microcontrollers", description: "Pico with WiFi & Bluetooth", image: "images/picow.png.png" },
    { id: 33, name: "Raspberry Pi Zero 2 W", price: 1600, category: "microcontrollers", description: "Zero 2 with WiFi & BT", image: "images/raspbarry02w.png.png" },
    { id: 34, name: "Raspberry Pi 4 (4GB)", price: 6000, category: "microcontrollers", description: "Pi 4 Model B - 4GB RAM", image: "images/raspbarrypi4,png.png" },
    { id: 35, name: "Raspberry Pi 4 (8GB)", price: 6800, category: "microcontrollers", description: "Pi 4 Model B - 8GB RAM", image: "images/raspbarrypi4,png.png" },
    { id: 36, name: "Raspberry Pi 5 (4GB)", price: 6200, category: "microcontrollers", description: "Latest Pi 5 - 4GB RAM", image: "images/raspbarrypi5.png.png" },
    { id: 37, name: "Raspberry Pi 5 (8GB)", price: 7200, category: "microcontrollers", description: "Latest Pi 5 - 8GB RAM", image: "images/raspbarrypi5.png.png" },
    { id: 38, name: "STM32 Blue Pill", price: 400, category: "microcontrollers", description: "STM32 board (with programmer)", image: "images/stm32.png.png" },
    { id: 39, name: "VC 02", price: 850, category: "microcontrollers", description: "Voice control module", image: "images/vc02.png.png" },
    
    // DISPLAYS
    { id: 40, name: "LCD 16x2", price: 120, category: "displays", description: "16x2 character LCD display", image: "images/lcd.png.png " },
    { id: 41, name: "LCD with I2C", price: 220, category: "displays", description: "16x2 LCD with I2C adapter", image: "images/lcd12c.png.png" },
    { id: 42, name: "OLED Display", price: 390, category: "displays", description: "0.96\" OLED I2C display", image: "images/oled.png.png" },
    
    // BOARDS
    { id: 43, name: "Breadboard", price: 90, category: "boards", description: "Full size breadboard 830 points", image: "images/breadboard.png.png" },
    { id: 44, name: "Half Breadboard", price: 70, category: "boards", description: "Half size breadboard 400 points", image: "images/smallboard.png.png" },
    { id: 45, name: "Mini Breadboard", price: 40, category: "boards", description: "Mini breadboard 170 points", image: "images/miniboard.png.png" },
    { id: 46, name: "Zero PCB", price: 90, category: "boards", description: "General purpose PCB board", image: "images/zero.png.png" },
    { id: 47, name: "Copper Sheet", price: 200, category: "boards", description: "Copper clad PCB sheet", image: "images/copper.png.png" },
    
    // MODULES
    { id: 48, name: "Motor Driver 4 Channel", price: 170, category: "modules", description: "L298N 4-channel driver", image: "images/4driver.png.png" },
    { id: 49, name: "Motor Driver 2 Channel", price: 150, category: "modules", description: "L298N 2-channel driver", image: "images/2driver,png.png" },
    { id: 50, name: "Small Motor Driver", price: 250, category: "modules", description: "Compact motor driver", image: "images/smalldriver.png.png" },
    { id: 51, name: "Buck Converter", price: 80, category: "modules", description: "Step-down DC-DC converter", image: "images/buck.png.png" },
    { id: 52, name: "Boost Converter", price: 120, category: "modules", description: "Step-up DC-DC converter", image: "images/boost,png.png" },
    { id: 53, name: "Remote Car Module", price: 190, category: "modules", description: "RF remote control module", image: "images/carmodule.png.png" },
    { id: 54, name: "Servo Driver 16 Channel", price: 300, category: "modules", description: "16-channel servo driver", image: "images/16channel.png.png" },
    { id: 55, name: "LoRa Module", price: 550, category: "modules", description: "Long range wireless module", image: "images/lora.png.png" },
    { id: 56, name: "nRF24L01 Antenna", price: 250, category: "modules", description: "2.4GHz wireless transceiver", image: "images/antenna.png.png" },
    { id: 57, name: "NEO GPS 6M", price: 290, category: "modules", description: "GPS module with antenna", image: "images/neo.png.png" },
    { id: 58, name: "C Type Charger Module", price: 60, category: "modules", description: "USB Type-C charging module", image: "images/typec.png.png" },
    
    // BATTERIES
    { id: 59, name: "Li-ion Battery", price: 80, category: "batteries", description: "18650 rechargeable battery", image: "images/battery.png.png" },
    { id: 60, name: "Single Battery Holder", price: 30, category: "batteries", description: "Single AA/AAA holder", image: "images/1holder.png.png" },
    { id: 61, name: "2 Battery Holder", price: 50, category: "batteries", description: "Dual AA/AAA holder", image: "images/2holder.png.png" },
    { id: 62, name: "4 Battery Holder", price: 80, category: "batteries", description: "Quad AA/AAA holder", image: "images/4holder.png.png" },
    { id: 63, name: "HW Battery", price: 25, category: "batteries", description: "High watt battery", image: "images/hw (1).png " },
    { id: 64, name: "Car Kit with Gear Motor", price: 550, category: "batteries", description: "Robot car chassis kit", image: "images/car.png.png" },
    
    // BLUETOOTH
    { id: 65, name: "HC-05", price: 270, category: "bluetooth", description: "Bluetooth master/slave module", image: "images/hc05.png.png" },
    { id: 66, name: "HC-06", price: 300, category: "bluetooth", description: "Bluetooth slave module", image: "images/hc06.png.png" },
    
    // OTHER MODULES
    { id: 67, name: "Jumper Cables", price: 80, category: "others", description: "M-M, M-F jumper wires bunch", image: "images/jumper.png.png" },
    { id: 68, name: "Solar Panel 5V", price: 100, category: "others", description: "5V solar panel", image: "images/solar.png.png" },
    { id: 69, name: "Solar Panel 12V-3W", price: 350, category: "others", description: "12V 3W solar panel", image: "images/solar12.png.png" },
    { id: 70, name: "Solar Panel 12V-5W", price: 500, category: "others", description: "12V 5W solar panel", image: "images/solar12.png.png" },
    { id: 71, name: "Drill Chuck", price: 200, category: "others", description: "Mini drill chuck", image: "images/chuck.png.png" },
    { id: 72, name: "Soldering Iron", price: 150, category: "others", description: "30W soldering iron", image: "images/solder.png.png" },
    { id: 73, name: "Lead & Flux", price: 100, category: "others", description: "Solder wire & flux kit", image: "images/lead.png.png" },
    { id: 74, name: "Multimeter", price: 170, category: "others", description: "Digital multimeter", image: "images/multimeter.png.png" },
    { id: 75, name: "Joystick Module", price: 80, category: "others", description: "Analog joystick controller", image: "images/joy.png.png" },
    { id: 76, name: "5V Relay", price: 70, category: "others", description: "Single channel relay", image: "images/relay.png.png" },
    { id: 77, name: "4 Channel Relay", price: 220, category: "others", description: "4-channel relay module", image: "images/4relay.png.png" },
    { id: 78, name: "Buzzer", price: 25, category: "others", description: "Active piezo buzzer", image: "images/buzzer.png.png" },
    { id: 79, name: "Resistor", price: 3, category: "others", description: "Carbon film resistor", image: "images/resistor.png" },
    { id: 80, name: "3x4 Keyboard", price: 80, category: "others", description: "3x4 matrix keypad", image: "images/3x4.png.png" },
    { id: 81, name: "4x4 Keyboard", price: 90, category: "others", description: "4x4 matrix keypad", image: "images/4x4.png.png" },
    { id: 82, name: "Arduino Cable", price: 70, category: "others", description: "USB A to B cable", image: "images/cable.png.png" },
    { id: 83, name: "ESP32 Cable", price: 90, category: "others", description: "Micro USB cable", image: "images/cable.png.png" },
    { id: 84, name: "Nano Cable", price: 70, category: "others", description: "Mini USB cable", image: "images/cable.png.png" },
    { id: 85, name: "Glue Gun", price: 250, category: "others", description: "Hot glue gun with sticks", image: "images/gun.png.png" },
    { id: 86, name: "Switch", price: 15, category: "others", description: "SPDT toggle switch", image: "images/switch.png.png" },
    { id: 87, name: "12V Adaptor", price: 190, category: "others", description: "12V DC power adapter 2A", image: "images/adaptor.png.png" },
    { id: 88, name: "Push Button", price: 7, category: "others", description: "Tactile push button", image: "images/push.png.png" },
    
    // EXCLUSIVE PRODUCTS
    { id: 89, name: "ATtiny85 Chip", price: 200, category: "exclusive", description: "ATtiny85 microcontroller", image: "images/attiny.png.png" },
    { id: 90, name: "8051 Chip", price: 130, category: "exclusive", description: "AT89C51 microcontroller", image: "images/8051.png.png" },
    { id: 91, name: "BO Motor", price: 70, category: "exclusive", description: "Battery operated DC motor (ONLY ONE)", image: "images/bomotor.png.png" },
    { id: 92, name: "Wheel", price: 30, category: "exclusive", description: "Robot wheel for BO motor ", image: "images/wheel.png" },
    { id: 93, name: "7805 Voltage Regulator", price: 20, category: "exclusive", description: "5V voltage regulator IC", image: "images/7805.png.png" },
    { id: 94, name: "RF433 Module", price: 90, category: "exclusive", description: "433MHz RF TX/RX module", image: "images/rf.png.png" },
    { id: 95, name: "BMS 3S/20A", price: 150, category: "exclusive", description: "Battery management system", image: "images/bms.png.png" },
    { id: 96, name: "Bug Strip", price: 15, category: "exclusive", description: "PCB terminal connector (PER STRIP)", image: "images/female.png.png" },
    { id: 97, name: "IC 555 Timer", price: 60, category: "exclusive", description: "NE555 timer IC with base", image: "images/555.png.png" },
    { id: 98, name: "Digital Volt/Amp Meter", price: 180, category: "exclusive", description: "Digital voltmeter ammeter", image: "images/digital.png.png" },
    { id: 99, name: "Segment Volt Meter", price: 140, category: "exclusive", description: "7-segment voltmeter", image: "images/segment.png.png" },
    { id: 100, name: "IRFZ44 MOSFET", price: 25, category: "exclusive", description: "N-channel power MOSFET", image: "images/mosfet.png.png" }
];
